import { Component, OnInit } from '@angular/core';
import { OpspotActivityObject, OpspotUser } from '../../../../app/interfaces/entities';
import { Session } from '../../../../app/services/session';
import { Client } from '../../../../app/services/api';

@Component({
  inputs: ['user'],
  selector: 'app-myjourney-widget',
  templateUrl: './myjourney-widget.component.html',
  styleUrls: ['./myjourney-widget.component.scss']
})
export class MyjourneyWidgetComponent implements OnInit {

  opspot = window.Opspot;
  user: OpspotUser;
  inProgress: boolean = false;

  entities = [{
    "guid": "1029255644886077450",
    "type": "object",
    "subtype": "video",
    "time_created": "1570769668",
    "time_updated": "1570769680",
    "container_guid": "1026476367534886929",
    "owner_guid": "1026476367534886929",
    "access_id": "2",
    "title": "testvideo",
    "featured": false,
    "featured_id": false,
    "ownerObj": {
      "guid": "1026476367534886929",
      "type": "user",
      "subtype": false,
      "time_created": "1570107036",
      "time_updated": false,
      "container_guid": "0",
      "owner_guid": "0",
      "site_guid": false,
      "access_id": "2",
      "tags": [],
      "name": "Abhijeet Salunkhe",
      "username": "abhijeet",
      "language": "en",
      "icontime": "1570764410",
      "legacy_guid": false,
      "featured_id": false,
      "banned": "no",
      "website": "",
      "briefdescription": "",
      "dob": "1991-DEC-18",
      "gender": "",
      "city": "",
      "merchant": false,
      "boostProPlus": false,
      "fb": false,
      "mature": "0",
      "monetized": "",
      "signup_method": false,
      "social_profiles": [],
      "feature_flags": false,
      "programs": [],
      "plus": false,
      "hashtags": false,
      "verified": false,
      "founder": false,
      "disabled_boost": false,
      "boost_autorotate": true,
      "categories": [],
      "wire_rewards": null,
      "pinned_posts": [],
      "is_mature": false,
      "mature_lock": false,
      "opted_in_hashtags": "0",
      "last_avatar_upload": "1570764394",
      "canary": false,
      "email": "abhijeet.salunkhe@aeione.com",
      "phone": "919867884320",
      "location": "",
      "general_info": [],
      "about": [],
      "work_experience": [],
      "education": [],
      "awards": [],
      "subscribed": "0",
      "subscriber": "0",
      "boost_rating": "1",
      "post_count": "0",
      "rewards": true,
      "p2p_media_enabled": false,
      "is_email_verified": false,
      "last_accepted_tos": "0",
      "eth_wallet": "",
      "rating": "1"
    },
    "category": false,
    "comments:count": false,
    "thumbs:up:count": 0,
    "thumbs:up:user_guids": false,
    "thumbs:down:count": 0,
    "thumbs:down:user_guids": false,
    "flags": {
      "mature": false
    },
    "wire_threshold": "0",
    "thumbnail": false,
    "cinemr_guid": "1029255644886077450",
    "license": false,
    "monetized": false,
    "mature": false,
    "boost_rejection_reason": -1,
    "thumbnail_src": "https:\/\/www.opsplt.com\/api\/v1\/media\/thumbnails\/1029255644886077450\/1570769680",
    "src": {
      "360.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/360.mp4",
      "720.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/720.mp4"
    },
    "play:count": 1,
    "description": "<?xml encoding=\"utf-8\" ?>\n",
    "rating": 2
  },
  {
    "guid": "1029255644886077450",
    "type": "object",
    "subtype": "video",
    "time_created": "1570769668",
    "time_updated": "1570769680",
    "container_guid": "1026476367534886929",
    "owner_guid": "1026476367534886929",
    "access_id": "2",
    "title": "testvideo",
    "featured": false,
    "featured_id": false,
    "ownerObj": {
      "guid": "1026476367534886929",
      "type": "user",
      "subtype": false,
      "time_created": "1570107036",
      "time_updated": false,
      "container_guid": "0",
      "owner_guid": "0",
      "site_guid": false,
      "access_id": "2",
      "tags": [],
      "name": "Abhijeet Salunkhe",
      "username": "abhijeet",
      "language": "en",
      "icontime": "1570764410",
      "legacy_guid": false,
      "featured_id": false,
      "banned": "no",
      "website": "",
      "briefdescription": "",
      "dob": "1991-DEC-18",
      "gender": "",
      "city": "",
      "merchant": false,
      "boostProPlus": false,
      "fb": false,
      "mature": "0",
      "monetized": "",
      "signup_method": false,
      "social_profiles": [],
      "feature_flags": false,
      "programs": [],
      "plus": false,
      "hashtags": false,
      "verified": false,
      "founder": false,
      "disabled_boost": false,
      "boost_autorotate": true,
      "categories": [],
      "wire_rewards": null,
      "pinned_posts": [],
      "is_mature": false,
      "mature_lock": false,
      "opted_in_hashtags": "0",
      "last_avatar_upload": "1570764394",
      "canary": false,
      "email": "abhijeet.salunkhe@aeione.com",
      "phone": "919867884320",
      "location": "",
      "general_info": [],
      "about": [],
      "work_experience": [],
      "education": [],
      "awards": [],
      "subscribed": "0",
      "subscriber": "0",
      "boost_rating": "1",
      "post_count": "0",
      "rewards": true,
      "p2p_media_enabled": false,
      "is_email_verified": false,
      "last_accepted_tos": "0",
      "eth_wallet": "",
      "rating": "1"
    },
    "category": false,
    "comments:count": false,
    "thumbs:up:count": 0,
    "thumbs:up:user_guids": false,
    "thumbs:down:count": 0,
    "thumbs:down:user_guids": false,
    "flags": {
      "mature": false
    },
    "wire_threshold": "0",
    "thumbnail": false,
    "cinemr_guid": "1029255644886077450",
    "license": false,
    "monetized": false,
    "mature": false,
    "boost_rejection_reason": -1,
    "thumbnail_src": "https:\/\/www.opsplt.com\/api\/v1\/media\/thumbnails\/1029255644886077450\/1570769680",
    "src": {
      "360.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/360.mp4",
      "720.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/720.mp4"
    },
    "play:count": 1,
    "description": "<?xml encoding=\"utf-8\" ?>\n",
    "rating": 2
  }, {
    "guid": "1029255644886077450",
    "type": "object",
    "subtype": "video",
    "time_created": "1570769668",
    "time_updated": "1570769680",
    "container_guid": "1026476367534886929",
    "owner_guid": "1026476367534886929",
    "access_id": "2",
    "title": "testvideo",
    "featured": false,
    "featured_id": false,
    "ownerObj": {
      "guid": "1026476367534886929",
      "type": "user",
      "subtype": false,
      "time_created": "1570107036",
      "time_updated": false,
      "container_guid": "0",
      "owner_guid": "0",
      "site_guid": false,
      "access_id": "2",
      "tags": [],
      "name": "Abhijeet Salunkhe",
      "username": "abhijeet",
      "language": "en",
      "icontime": "1570764410",
      "legacy_guid": false,
      "featured_id": false,
      "banned": "no",
      "website": "",
      "briefdescription": "",
      "dob": "1991-DEC-18",
      "gender": "",
      "city": "",
      "merchant": false,
      "boostProPlus": false,
      "fb": false,
      "mature": "0",
      "monetized": "",
      "signup_method": false,
      "social_profiles": [],
      "feature_flags": false,
      "programs": [],
      "plus": false,
      "hashtags": false,
      "verified": false,
      "founder": false,
      "disabled_boost": false,
      "boost_autorotate": true,
      "categories": [],
      "wire_rewards": null,
      "pinned_posts": [],
      "is_mature": false,
      "mature_lock": false,
      "opted_in_hashtags": "0",
      "last_avatar_upload": "1570764394",
      "canary": false,
      "email": "abhijeet.salunkhe@aeione.com",
      "phone": "919867884320",
      "location": "",
      "general_info": [],
      "about": [],
      "work_experience": [],
      "education": [],
      "awards": [],
      "subscribed": "0",
      "subscriber": "0",
      "boost_rating": "1",
      "post_count": "0",
      "rewards": true,
      "p2p_media_enabled": false,
      "is_email_verified": false,
      "last_accepted_tos": "0",
      "eth_wallet": "",
      "rating": "1"
    },
    "category": false,
    "comments:count": false,
    "thumbs:up:count": 0,
    "thumbs:up:user_guids": false,
    "thumbs:down:count": 0,
    "thumbs:down:user_guids": false,
    "flags": {
      "mature": false
    },
    "wire_threshold": "0",
    "thumbnail": false,
    "cinemr_guid": "1029255644886077450",
    "license": false,
    "monetized": false,
    "mature": false,
    "boost_rejection_reason": -1,
    "thumbnail_src": "https:\/\/www.opsplt.com\/api\/v1\/media\/thumbnails\/1029255644886077450\/1570769680",
    "src": {
      "360.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/360.mp4",
      "720.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/720.mp4"
    },
    "play:count": 1,
    "description": "<?xml encoding=\"utf-8\" ?>\n",
    "rating": 2
  }, {
    "guid": "1029255644886077450",
    "type": "object",
    "subtype": "video",
    "time_created": "1570769668",
    "time_updated": "1570769680",
    "container_guid": "1026476367534886929",
    "owner_guid": "1026476367534886929",
    "access_id": "2",
    "title": "testvideo",
    "featured": false,
    "featured_id": false,
    "ownerObj": {
      "guid": "1026476367534886929",
      "type": "user",
      "subtype": false,
      "time_created": "1570107036",
      "time_updated": false,
      "container_guid": "0",
      "owner_guid": "0",
      "site_guid": false,
      "access_id": "2",
      "tags": [],
      "name": "Abhijeet Salunkhe",
      "username": "abhijeet",
      "language": "en",
      "icontime": "1570764410",
      "legacy_guid": false,
      "featured_id": false,
      "banned": "no",
      "website": "",
      "briefdescription": "",
      "dob": "1991-DEC-18",
      "gender": "",
      "city": "",
      "merchant": false,
      "boostProPlus": false,
      "fb": false,
      "mature": "0",
      "monetized": "",
      "signup_method": false,
      "social_profiles": [],
      "feature_flags": false,
      "programs": [],
      "plus": false,
      "hashtags": false,
      "verified": false,
      "founder": false,
      "disabled_boost": false,
      "boost_autorotate": true,
      "categories": [],
      "wire_rewards": null,
      "pinned_posts": [],
      "is_mature": false,
      "mature_lock": false,
      "opted_in_hashtags": "0",
      "last_avatar_upload": "1570764394",
      "canary": false,
      "email": "abhijeet.salunkhe@aeione.com",
      "phone": "919867884320",
      "location": "",
      "general_info": [],
      "about": [],
      "work_experience": [],
      "education": [],
      "awards": [],
      "subscribed": "0",
      "subscriber": "0",
      "boost_rating": "1",
      "post_count": "0",
      "rewards": true,
      "p2p_media_enabled": false,
      "is_email_verified": false,
      "last_accepted_tos": "0",
      "eth_wallet": "",
      "rating": "1"
    },
    "category": false,
    "comments:count": false,
    "thumbs:up:count": 0,
    "thumbs:up:user_guids": false,
    "thumbs:down:count": 0,
    "thumbs:down:user_guids": false,
    "flags": {
      "mature": false
    },
    "wire_threshold": "0",
    "thumbnail": false,
    "cinemr_guid": "1029255644886077450",
    "license": false,
    "monetized": false,
    "mature": false,
    "boost_rejection_reason": -1,
    "thumbnail_src": "https:\/\/www.opsplt.com\/api\/v1\/media\/thumbnails\/1029255644886077450\/1570769680",
    "src": {
      "360.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/360.mp4",
      "720.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/720.mp4"
    },
    "play:count": 1,
    "description": "<?xml encoding=\"utf-8\" ?>\n",
    "rating": 2
  }, {
    "guid": "1029255644886077450",
    "type": "object",
    "subtype": "video",
    "time_created": "1570769668",
    "time_updated": "1570769680",
    "container_guid": "1026476367534886929",
    "owner_guid": "1026476367534886929",
    "access_id": "2",
    "title": "testvideo",
    "featured": false,
    "featured_id": false,
    "ownerObj": {
      "guid": "1026476367534886929",
      "type": "user",
      "subtype": false,
      "time_created": "1570107036",
      "time_updated": false,
      "container_guid": "0",
      "owner_guid": "0",
      "site_guid": false,
      "access_id": "2",
      "tags": [],
      "name": "Abhijeet Salunkhe",
      "username": "abhijeet",
      "language": "en",
      "icontime": "1570764410",
      "legacy_guid": false,
      "featured_id": false,
      "banned": "no",
      "website": "",
      "briefdescription": "",
      "dob": "1991-DEC-18",
      "gender": "",
      "city": "",
      "merchant": false,
      "boostProPlus": false,
      "fb": false,
      "mature": "0",
      "monetized": "",
      "signup_method": false,
      "social_profiles": [],
      "feature_flags": false,
      "programs": [],
      "plus": false,
      "hashtags": false,
      "verified": false,
      "founder": false,
      "disabled_boost": false,
      "boost_autorotate": true,
      "categories": [],
      "wire_rewards": null,
      "pinned_posts": [],
      "is_mature": false,
      "mature_lock": false,
      "opted_in_hashtags": "0",
      "last_avatar_upload": "1570764394",
      "canary": false,
      "email": "abhijeet.salunkhe@aeione.com",
      "phone": "919867884320",
      "location": "",
      "general_info": [],
      "about": [],
      "work_experience": [],
      "education": [],
      "awards": [],
      "subscribed": "0",
      "subscriber": "0",
      "boost_rating": "1",
      "post_count": "0",
      "rewards": true,
      "p2p_media_enabled": false,
      "is_email_verified": false,
      "last_accepted_tos": "0",
      "eth_wallet": "",
      "rating": "1"
    },
    "category": false,
    "comments:count": false,
    "thumbs:up:count": 0,
    "thumbs:up:user_guids": false,
    "thumbs:down:count": 0,
    "thumbs:down:user_guids": false,
    "flags": {
      "mature": false
    },
    "wire_threshold": "0",
    "thumbnail": false,
    "cinemr_guid": "1029255644886077450",
    "license": false,
    "monetized": false,
    "mature": false,
    "boost_rejection_reason": -1,
    "thumbnail_src": "https:\/\/www.opsplt.com\/api\/v1\/media\/thumbnails\/1029255644886077450\/1570769680",
    "src": {
      "360.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/360.mp4",
      "720.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/720.mp4"
    },
    "play:count": 1,
    "description": "<?xml encoding=\"utf-8\" ?>\n",
    "rating": 2
  }, {
    "guid": "1029255644886077450",
    "type": "object",
    "subtype": "video",
    "time_created": "1570769668",
    "time_updated": "1570769680",
    "container_guid": "1026476367534886929",
    "owner_guid": "1026476367534886929",
    "access_id": "2",
    "title": "testvideo",
    "featured": false,
    "featured_id": false,
    "ownerObj": {
      "guid": "1026476367534886929",
      "type": "user",
      "subtype": false,
      "time_created": "1570107036",
      "time_updated": false,
      "container_guid": "0",
      "owner_guid": "0",
      "site_guid": false,
      "access_id": "2",
      "tags": [],
      "name": "Abhijeet Salunkhe",
      "username": "abhijeet",
      "language": "en",
      "icontime": "1570764410",
      "legacy_guid": false,
      "featured_id": false,
      "banned": "no",
      "website": "",
      "briefdescription": "",
      "dob": "1991-DEC-18",
      "gender": "",
      "city": "",
      "merchant": false,
      "boostProPlus": false,
      "fb": false,
      "mature": "0",
      "monetized": "",
      "signup_method": false,
      "social_profiles": [],
      "feature_flags": false,
      "programs": [],
      "plus": false,
      "hashtags": false,
      "verified": false,
      "founder": false,
      "disabled_boost": false,
      "boost_autorotate": true,
      "categories": [],
      "wire_rewards": null,
      "pinned_posts": [],
      "is_mature": false,
      "mature_lock": false,
      "opted_in_hashtags": "0",
      "last_avatar_upload": "1570764394",
      "canary": false,
      "email": "abhijeet.salunkhe@aeione.com",
      "phone": "919867884320",
      "location": "",
      "general_info": [],
      "about": [],
      "work_experience": [],
      "education": [],
      "awards": [],
      "subscribed": "0",
      "subscriber": "0",
      "boost_rating": "1",
      "post_count": "0",
      "rewards": true,
      "p2p_media_enabled": false,
      "is_email_verified": false,
      "last_accepted_tos": "0",
      "eth_wallet": "",
      "rating": "1"
    },
    "category": false,
    "comments:count": false,
    "thumbs:up:count": 0,
    "thumbs:up:user_guids": false,
    "thumbs:down:count": 0,
    "thumbs:down:user_guids": false,
    "flags": {
      "mature": false
    },
    "wire_threshold": "0",
    "thumbnail": false,
    "cinemr_guid": "1029255644886077450",
    "license": false,
    "monetized": false,
    "mature": false,
    "boost_rejection_reason": -1,
    "thumbnail_src": "https:\/\/www.opsplt.com\/api\/v1\/media\/thumbnails\/1029255644886077450\/1570769680",
    "src": {
      "360.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/360.mp4",
      "720.mp4": "https:\/\/opspot-videos-02.s3.amazonaws.com\/1029255644886077450\/720.mp4"
    },
    "play:count": 1,
    "description": "<?xml encoding=\"utf-8\" ?>\n",
    "rating": 2
  }
  ];

  params: any = {
    taxonomies: 'activity',
    offset: '',
    limit: 10,
    q: ''
  }

  constructor(
    public session: Session,
    public client: Client,
  ) { }

  ngOnInit() {
    this.load();
  }

  load() {
    if (this.inProgress) {
      return false;
    }

    this.params.q = '#myjourney' + this.user.username;
    this.inProgress = true;

    this.client.get('api/v1/search', this.params)
      .then((resp: any) => {
        console.log("response: ", resp);
        //  for (let entity of this.entities) {
        //   if (entity.custom_data.length) {
        //     for (var i = 0; i < entity.custom_data.length; i++) {
        //       this.entities.push(entity.custom_data[i]);
        //     }
        //   } else {
        //     this.entities.push(entity.custom_data);
        //   }
        // }
        this.inProgress = false;
      })
      .catch(function (e) {
        this.inProgress = false;
      });
  }
}
