import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { Client } from '../../services/api';

@Component({
  selector: 'app-portfolio',
  templateUrl: './portfolio.component.html',
  styleUrls: ['./portfolio.component.scss']
})
export class PortfolioComponent implements OnInit, OnDestroy {

  paramsSub: Subscription;
  /**temp variables */
  offset: string = '';
  q: string = '';
  type: string = '';
  entities = [{
		"guid": "1026022979215454208",
		"type": "object",
		"subtype": "image",
		"time_created": "1572552000",
		"time_updated": "1569998980",
		"container_guid": "989399767404519427",
		"owner_guid": "989399767404519427",
		"access_id": "2",
		"nsfw": [],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "Day 31 of the 31 Days of Halloween. \nHere is a final last minute costume idea. \nHappy Halloween",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "989399767404519427",
			"type": "user",
			"subtype": false,
			"time_created": "1561267286",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": [],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "DivaDoll",
			"username": "divadoll",
			"language": "en",
			"icontime": "1569982805",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Hello, I'm Mrs. Doll,  I live in Minnesota with my amazing husband. We're organic, free range, hippies, who believe in a decentralized living.\n\nI love to research, explore my natural environment, and create.\n\nMy goal for this channel is to help inspire others. \n\nI am also interested in sharing art and other things that I find eye opening and spiritually engaging. \n\nI spent a fair amount of time off-grid and recently re-entered society.\n\nIn my spare time, I substitute as a Backyard Tourist, and volunteer my services as a Freelance Know-It-All. \n\n",
			"dob": "",
			"gender": "",
			"city": "Mankato",
			"merchant": {
				"service": "stripe",
				"id": "acct_1FNZ9iAfYt6GfvhP"
			},
			"boostProPlus": false,
			"fb": false,
			"mature": "0",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [],
			"feature_flags": false,
			"programs": [],
			"plus": true,
			"hashtags": false,
			"verified": true,
			"founder": false,
			"disabled_boost": true,
			"boost_autorotate": true,
			"categories": [],
			"wire_rewards": {
				"description": "",
				"rewards": {
					"points": [],
					"money": [],
					"tokens": []
				}
			},
			"pinned_posts": ["1025687921954775040", "1025688964679720960", "1025687419265531904"],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "1",
			"last_avatar_upload": "1569982805",
			"canary": true,
			"theme": "light",
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"chat": true,
			"urn": "urn:user:989399767404519427",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "2",
			"pro": false,
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"onchain_booster": "0",
			"eth_wallet": "0xdb170a3331474ee0750621bff583e4a437aa8c35",
			"rating": "1"
		},
		"entity_guid": "1025713606068539412",
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 0,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false
		},
		"wire_threshold": "0",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1026022979215454208\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyNjAyMjk3OTIxNTQ1NDIwOFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.m-RUgYxVFuK0YHmmy1Xg-YF6ctF2-87Q0kGQ_HMmmjo",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 564,
		"height": 752,
		"gif": false,
		"time_sent": 1569998940,
		"urn": "urn:image:1026022979215454208",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1026022979215454208\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyNjAyMjk3OTIxNTQ1NDIwOFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.m-RUgYxVFuK0YHmmy1Xg-YF6ctF2-87Q0kGQ_HMmmjo",
		"description": null
	}, {
		"guid": "1026020639886831616",
		"type": "object",
		"subtype": "image",
		"time_created": "1572150600",
		"time_updated": "1569998397",
		"container_guid": "989399767404519427",
		"owner_guid": "989399767404519427",
		"access_id": "2",
		"nsfw": [],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "Day 26 of the 31 Days of Halloween. I will be posting cool costumes all month long.\nDay 26: Alice in Wonderland, a family costume",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "989399767404519427",
			"type": "user",
			"subtype": false,
			"time_created": "1561267286",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": [],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "DivaDoll",
			"username": "divadoll",
			"language": "en",
			"icontime": "1569982805",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Hello, I'm Mrs. Doll,  I live in Minnesota with my amazing husband. We're organic, free range, hippies, who believe in a decentralized living.\n\nI love to research, explore my natural environment, and create.\n\nMy goal for this channel is to help inspire others. \n\nI am also interested in sharing art and other things that I find eye opening and spiritually engaging. \n\nI spent a fair amount of time off-grid and recently re-entered society.\n\nIn my spare time, I substitute as a Backyard Tourist, and volunteer my services as a Freelance Know-It-All. \n\n",
			"dob": "",
			"gender": "",
			"city": "Mankato",
			"merchant": {
				"service": "stripe",
				"id": "acct_1FNZ9iAfYt6GfvhP"
			},
			"boostProPlus": false,
			"fb": false,
			"mature": "0",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [],
			"feature_flags": false,
			"programs": [],
			"plus": true,
			"hashtags": false,
			"verified": true,
			"founder": false,
			"disabled_boost": true,
			"boost_autorotate": true,
			"categories": [],
			"wire_rewards": {
				"description": "",
				"rewards": {
					"points": [],
					"money": [],
					"tokens": []
				}
			},
			"pinned_posts": ["1025687921954775040", "1025688964679720960", "1025687419265531904"],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "1",
			"last_avatar_upload": "1569982805",
			"canary": true,
			"theme": "light",
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"chat": true,
			"urn": "urn:user:989399767404519427",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "2",
			"pro": false,
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"onchain_booster": "0",
			"eth_wallet": "0xdb170a3331474ee0750621bff583e4a437aa8c35",
			"rating": "1"
		},
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 0,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false
		},
		"wire_threshold": "0",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1026020639886831616\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyNjAyMDYzOTg4NjgzMTYxNlwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.cqFJmEbcj2fY1yML4l-VdS367sr8JmkkhEFRXPcS0MQ",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 564,
		"height": 599,
		"gif": false,
		"time_sent": 1569998383,
		"urn": "urn:image:1026020639886831616",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1026020639886831616\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyNjAyMDYzOTg4NjgzMTYxNlwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.cqFJmEbcj2fY1yML4l-VdS367sr8JmkkhEFRXPcS0MQ",
		"description": null
	}, {
		"guid": "1025335945555779584",
		"type": "object",
		"subtype": "image",
		"time_created": "1572091200",
		"time_updated": "1569835662",
		"container_guid": "1011430374300983299",
		"owner_guid": "1011430374300983299",
		"access_id": "2",
		"nsfw": [1, 2],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "Orcish Harem \u2014 if you like it, you may also like this orc\/human interracial couple:  https:\/\/www.minds.com\/newsfeed\/1020884003067445248\n\n\ud83c\udf96 If you're a good guy who enjoys drawings like this, you can give it a thumbs-up, comment, subscribe, wire me some lightning, or buy me a Ko-Fi ( https:\/\/ko-fi.com\/malcolmd ).\n\nHaving defeated an orcish warchief, a human assumes the leadership of the chief's savage orc tribe. By virtue of his victory, and with a little cultural assimilation, the human claims the deceased chief's wives and\/or daughters. Of course, his position won't be stable until he can breed them, a task that he begins with relish.\n\n#hentai #nsfw #interracial #orc #fantasy #bigbreasts #tits #sumtiddy #tiddies #chubby #fat #thicc #voluptuous #humanxorc #interspecies #harem #breeding #ahegao #DungeonsandDragons #D&D #WorldofWarcraft #WoW #hairypubes #hairy #bush #\u5192\u967a\u5bb6 #\u7570\u7a2e\u59e6 #\u30d5\u30a1\u30f3\u30bf\u30b8\u30fc #\u30aa\u30fc\u30af\u5a18 #\u304d\u308c\u3044\u306a\u30a8\u30ed \u7acb\u3061\u30d0\u30c3\u30af #\u719f\u5973 #\u6bcd\u6027\u7684\u5973\u4f53 #\u9670\u6bdb #\u30ae\u30e3\u30e9\u30f3\u30c9\u30a5\u30fc #\u7206\u4e73 #\u5de8\u4e73 #\u5782\u308c\u4e73 #\u3080\u3061\u3080\u3061 #\u307d\u3063\u3061\u3083\u308a #\u30a2\u30d8\u9854 #MalcolmDouglas",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "1011430374300983299",
			"type": "user",
			"subtype": false,
			"time_created": "1566519792",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": [],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "MalcolmD",
			"username": "malcolmd",
			"language": "en",
			"icontime": "1567030876",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Hentai artist",
			"dob": "",
			"gender": "",
			"city": "",
			"merchant": false,
			"boostProPlus": false,
			"fb": false,
			"mature": "1",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [],
			"feature_flags": false,
			"programs": [],
			"plus": false,
			"hashtags": false,
			"verified": false,
			"founder": false,
			"disabled_boost": false,
			"boost_autorotate": true,
			"categories": [],
			"wire_rewards": null,
			"pinned_posts": [],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "7",
			"last_avatar_upload": "1566521762",
			"canary": true,
			"theme": false,
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"urn": "urn:user:1011430374300983299",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "1",
			"pro": false,
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"onchain_booster": "0",
			"eth_wallet": "",
			"rating": "1"
		},
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 0,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false
		},
		"wire_threshold": "",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1025335945555779584\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyNTMzNTk0NTU1NTc3OTU4NFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.5U_W-mtjP3gErPzQV3XbDU3ckG3vQZezIJ-eD-xLkEM",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 1920,
		"height": 1080,
		"gif": false,
		"time_sent": 1569835139,
		"urn": "urn:image:1025335945555779584",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1025335945555779584\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyNTMzNTk0NTU1NTc3OTU4NFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.5U_W-mtjP3gErPzQV3XbDU3ckG3vQZezIJ-eD-xLkEM",
		"description": null
	}, {
		"guid": "1022867272742191104",
		"type": "object",
		"subtype": "image",
		"time_created": "1572012000",
		"time_updated": "1569247436",
		"container_guid": "902355209638912004",
		"owner_guid": "902355209638912004",
		"access_id": "2",
		"nsfw": [],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "MyPlate = MyDiabetes\nMyPlate is the current nutrition guide published by the USDA Center for Nutrition Policy and Promotion. It replaced the USDA's MyPyramid guide in 2011, ending 19 years of USDA food pyramid diagrams. However, diabetes (and related metabolic disorders) are epidemic which makes the higher carbohydrate ratio a poor fit for today's needs.\n#nutrition",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "902355209638912004",
			"type": "user",
			"subtype": false,
			"time_created": "1540514246",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": ["medicine", "health", "science", "stem", "nutrition"],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "Dr. Cassone",
			"username": "drcassone",
			"language": "en",
			"icontime": "1568521928",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Cassone\n(pronouced: kuh\u00b7so\u00b7nee)\n\nWelcome to my favorite social media site. I am here on Minds as an educator with the goal of creating great content for you.\n\n#medicine #science #nutrition \n\nABOUT\nI hold two master\u2019s degrees in health sciences, a PhD in clinical nutrition, a second doctorate in integrative medicine (DAOM), and am a board certified licensed primary care provider in the state of California running a thriving private practice. I also have a teaching position at South Baylo University educating\u00a0licensed providers, have written three books, and am the owner and operator of a private gym called Range of Motion which I opened in 2000.\n\n\u201cAs a scientist and a researcher, it has been my life\u2019s work to sort effectual from ineffectual treatment models. As a doctor, it is my art to investigate the complex origins of each patient\u2019s condition and to apply techniques of corrective physiology. It is only by understanding and treating the root cause that long term health is possible.\u201d - Dr. Cassone\n\nMAIN WEBSITE\nhttps:\/\/www.cassonewellness.com\/ \n________________________________\nGROUPS\n\nFERMENTED FOODS\nhttps:\/\/www.minds.com\/groups\/profile\/909827446092017664\/feed\n\nRESET Food Plan\nhttps:\/\/www.minds.com\/groups\/profile\/907272216328880128\/feed\n\nMEDICINE: Quiz Yourself\nhttps:\/\/www.minds.com\/groups\/profile\/938541470676492288\/feed\n\nSMOOTHIES\nhttps:\/\/www.minds.com\/groups\/profile\/912825469371117568\/feed\n_____________________________\nTOP CONTRIBUTORS\n\n@Annaroper\n@GreenDeen\n@FloatingOnSmiles\n@peninsolar\n@delastman\n@MinnieApolis\n@IndianaJames\n@TheronH\n@mindofmyown\n@FaizanKhan\n@mindsplus\n@drpatricklockwood\n@Luculent\n@Willieleev1971\n@nkrpoetry\n_____________________________\nDisclaimer:\n[Dr. Cassone's title of \"doctor\" or \u201cDr.\u201d refers to the above mentioned academic degrees. All content posted is for general informational purposes only and should not be used to self-diagnose and it is not a substitute for a medical exam, cure, treatment, diagnosis, prescription, or recommendation. Posted content and comments do not create a doctor-patient relationship between Dr. Cassone and the viewer.  Those who view or engage should not make any lifestyle changes before first consulting a physician and obtaining a medical exam, diagnosis, and personal recommendation.  Always seek the advice of a physician, or other qualified health provider, with any questions regarding medical conditions. Dr. Cassone is not liable or responsible for any advice, course of treatment, diagnosis or any other information, services or products you obtain.]",
			"dob": "",
			"gender": "",
			"city": "Temecula, Ca.",
			"merchant": false,
			"boostProPlus": false,
			"fb": false,
			"mature": "0",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [{
				"key": "other",
				"value": "https:\/\/www.amazon.com\/Dr.-Cassone\/e\/B00J2HJX6Y\/ref=sr_ntt_srch_lnk_1?qid=1542295447&sr=8-1"
			}],
			"feature_flags": false,
			"programs": [],
			"plus": false,
			"hashtags": false,
			"verified": true,
			"founder": false,
			"disabled_boost": true,
			"boost_autorotate": false,
			"categories": [],
			"wire_rewards": {
				"description": "Thank you for your support! ",
				"rewards": {
					"points": [],
					"money": [],
					"tokens": [{
						"amount": "1",
						"description": "I very much appreciate your kindness and will use your donation to post awesome content."
					}, {
						"amount": "5",
						"description": "I will mention your channel in a post as a great show of gratitude. If you're lucky I will boost it."
					}, {
						"amount": "10",
						"description": "Your name will appear in my bio section as a supporter for the next six months. "
					}]
				}
			},
			"pinned_posts": ["946612051418996736", "941137053490614272", "964335278414299136"],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "8",
			"last_avatar_upload": "0",
			"canary": true,
			"theme": "dark",
			"onchain_booster": "1563466121",
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"chat": true,
			"urn": "urn:user:902355209638912004",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "1",
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"eth_wallet": "0x9851dad5c623558e0c9d2292f54f49ff019d9dd1",
			"rating": "1"
		},
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 0,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false
		},
		"wire_threshold": "0",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1022867272742191104\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMjg2NzI3Mjc0MjE5MTEwNFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.gg0U7zLgqZ-pjyQlFy_B8vztEpbiunOqJxpIUEa_vGM",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 1280,
		"height": 1174,
		"gif": false,
		"time_sent": 1569246561,
		"urn": "urn:image:1022867272742191104",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1022867272742191104\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMjg2NzI3Mjc0MjE5MTEwNFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.gg0U7zLgqZ-pjyQlFy_B8vztEpbiunOqJxpIUEa_vGM",
		"description": null
	}, {
		"guid": "1022524239391735808",
		"type": "object",
		"subtype": "image",
		"time_created": "1571842800",
		"time_updated": "1569165501",
		"container_guid": "902355209638912004",
		"owner_guid": "902355209638912004",
		"access_id": "2",
		"nsfw": [],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "\"Reflux is a disease, not a bad meal choice.\" - Johnson & Johnson\nThis photo, along with the quote, is on an ad campaign selling truly barbaric methods for treating acid reflux. Elaborate, expensive, and damaging while not addressing any causative factors. Instead, reduce irritating foods and use treatments designed to improve digestive functions.\n\n(Btw, the stomach is not located that far down.)\n#medicine #nutrition #health\n",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "902355209638912004",
			"type": "user",
			"subtype": false,
			"time_created": "1540514246",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": ["medicine", "health", "science", "stem", "nutrition"],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "Dr. Cassone",
			"username": "drcassone",
			"language": "en",
			"icontime": "1568521928",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Cassone\n(pronouced: kuh\u00b7so\u00b7nee)\n\nWelcome to my favorite social media site. I am here on Minds as an educator with the goal of creating great content for you.\n\n#medicine #science #nutrition \n\nABOUT\nI hold two master\u2019s degrees in health sciences, a PhD in clinical nutrition, a second doctorate in integrative medicine (DAOM), and am a board certified licensed primary care provider in the state of California running a thriving private practice. I also have a teaching position at South Baylo University educating\u00a0licensed providers, have written three books, and am the owner and operator of a private gym called Range of Motion which I opened in 2000.\n\n\u201cAs a scientist and a researcher, it has been my life\u2019s work to sort effectual from ineffectual treatment models. As a doctor, it is my art to investigate the complex origins of each patient\u2019s condition and to apply techniques of corrective physiology. It is only by understanding and treating the root cause that long term health is possible.\u201d - Dr. Cassone\n\nMAIN WEBSITE\nhttps:\/\/www.cassonewellness.com\/ \n________________________________\nGROUPS\n\nFERMENTED FOODS\nhttps:\/\/www.minds.com\/groups\/profile\/909827446092017664\/feed\n\nRESET Food Plan\nhttps:\/\/www.minds.com\/groups\/profile\/907272216328880128\/feed\n\nMEDICINE: Quiz Yourself\nhttps:\/\/www.minds.com\/groups\/profile\/938541470676492288\/feed\n\nSMOOTHIES\nhttps:\/\/www.minds.com\/groups\/profile\/912825469371117568\/feed\n_____________________________\nTOP CONTRIBUTORS\n\n@Annaroper\n@GreenDeen\n@FloatingOnSmiles\n@peninsolar\n@delastman\n@MinnieApolis\n@IndianaJames\n@TheronH\n@mindofmyown\n@FaizanKhan\n@mindsplus\n@drpatricklockwood\n@Luculent\n@Willieleev1971\n@nkrpoetry\n_____________________________\nDisclaimer:\n[Dr. Cassone's title of \"doctor\" or \u201cDr.\u201d refers to the above mentioned academic degrees. All content posted is for general informational purposes only and should not be used to self-diagnose and it is not a substitute for a medical exam, cure, treatment, diagnosis, prescription, or recommendation. Posted content and comments do not create a doctor-patient relationship between Dr. Cassone and the viewer.  Those who view or engage should not make any lifestyle changes before first consulting a physician and obtaining a medical exam, diagnosis, and personal recommendation.  Always seek the advice of a physician, or other qualified health provider, with any questions regarding medical conditions. Dr. Cassone is not liable or responsible for any advice, course of treatment, diagnosis or any other information, services or products you obtain.]",
			"dob": "",
			"gender": "",
			"city": "Temecula, Ca.",
			"merchant": false,
			"boostProPlus": false,
			"fb": false,
			"mature": "0",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [{
				"key": "other",
				"value": "https:\/\/www.amazon.com\/Dr.-Cassone\/e\/B00J2HJX6Y\/ref=sr_ntt_srch_lnk_1?qid=1542295447&sr=8-1"
			}],
			"feature_flags": false,
			"programs": [],
			"plus": false,
			"hashtags": false,
			"verified": true,
			"founder": false,
			"disabled_boost": true,
			"boost_autorotate": false,
			"categories": [],
			"wire_rewards": {
				"description": "Thank you for your support! ",
				"rewards": {
					"points": [],
					"money": [],
					"tokens": [{
						"amount": "1",
						"description": "I very much appreciate your kindness and will use your donation to post awesome content."
					}, {
						"amount": "5",
						"description": "I will mention your channel in a post as a great show of gratitude. If you're lucky I will boost it."
					}, {
						"amount": "10",
						"description": "Your name will appear in my bio section as a supporter for the next six months. "
					}]
				}
			},
			"pinned_posts": ["946612051418996736", "941137053490614272", "964335278414299136"],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "8",
			"last_avatar_upload": "0",
			"canary": true,
			"theme": "dark",
			"onchain_booster": "1563466121",
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"chat": true,
			"urn": "urn:user:902355209638912004",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "1",
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"eth_wallet": "0x9851dad5c623558e0c9d2292f54f49ff019d9dd1",
			"rating": "1"
		},
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 0,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false
		},
		"wire_threshold": "0",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1022524239391735808\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMjUyNDIzOTM5MTczNTgwOFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.UNdgaKYE2Sr-dbI5gLf_7Z9ADrS3LyHS4PKLS5q5yRE",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 800,
		"height": 800,
		"gif": false,
		"time_sent": 1569164776,
		"urn": "urn:image:1022524239391735808",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1022524239391735808\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMjUyNDIzOTM5MTczNTgwOFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.UNdgaKYE2Sr-dbI5gLf_7Z9ADrS3LyHS4PKLS5q5yRE",
		"description": null
	}, {
		"guid": "1022521168192323584",
		"type": "object",
		"subtype": "image",
		"time_created": "1571756400",
		"time_updated": "1569164503",
		"container_guid": "902355209638912004",
		"owner_guid": "902355209638912004",
		"access_id": "2",
		"nsfw": [],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "Your Doctor is Wrong\nAt least most of the time when they prescribe antacid medications. \n\nThere is (almost) never a time when there is too much acid during food intake (digestion). Hiatal herniation, gastritis, pyloric stenosis, etc. will complicate the presentation but most common is hypochlorhydria (under-production of acid) regardless the symptoms. \n\nOccasionally, I see patients that are producing too much acid relative to bolus (too much acid when there is no food but not enough acid when there is food). For those patients, they can stay on the medications, to cover them between meals, but I add an HCl\/enzyme when they eat and treat the underlying cause. They only time I don't use an HCl product is if there is gastritis (indicated by lingering pain spots).\n#medicine #health",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "902355209638912004",
			"type": "user",
			"subtype": false,
			"time_created": "1540514246",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": ["medicine", "health", "science", "stem", "nutrition"],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "Dr. Cassone",
			"username": "drcassone",
			"language": "en",
			"icontime": "1568521928",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Cassone\n(pronouced: kuh\u00b7so\u00b7nee)\n\nWelcome to my favorite social media site. I am here on Minds as an educator with the goal of creating great content for you.\n\n#medicine #science #nutrition \n\nABOUT\nI hold two master\u2019s degrees in health sciences, a PhD in clinical nutrition, a second doctorate in integrative medicine (DAOM), and am a board certified licensed primary care provider in the state of California running a thriving private practice. I also have a teaching position at South Baylo University educating\u00a0licensed providers, have written three books, and am the owner and operator of a private gym called Range of Motion which I opened in 2000.\n\n\u201cAs a scientist and a researcher, it has been my life\u2019s work to sort effectual from ineffectual treatment models. As a doctor, it is my art to investigate the complex origins of each patient\u2019s condition and to apply techniques of corrective physiology. It is only by understanding and treating the root cause that long term health is possible.\u201d - Dr. Cassone\n\nMAIN WEBSITE\nhttps:\/\/www.cassonewellness.com\/ \n________________________________\nGROUPS\n\nFERMENTED FOODS\nhttps:\/\/www.minds.com\/groups\/profile\/909827446092017664\/feed\n\nRESET Food Plan\nhttps:\/\/www.minds.com\/groups\/profile\/907272216328880128\/feed\n\nMEDICINE: Quiz Yourself\nhttps:\/\/www.minds.com\/groups\/profile\/938541470676492288\/feed\n\nSMOOTHIES\nhttps:\/\/www.minds.com\/groups\/profile\/912825469371117568\/feed\n_____________________________\nTOP CONTRIBUTORS\n\n@Annaroper\n@GreenDeen\n@FloatingOnSmiles\n@peninsolar\n@delastman\n@MinnieApolis\n@IndianaJames\n@TheronH\n@mindofmyown\n@FaizanKhan\n@mindsplus\n@drpatricklockwood\n@Luculent\n@Willieleev1971\n@nkrpoetry\n_____________________________\nDisclaimer:\n[Dr. Cassone's title of \"doctor\" or \u201cDr.\u201d refers to the above mentioned academic degrees. All content posted is for general informational purposes only and should not be used to self-diagnose and it is not a substitute for a medical exam, cure, treatment, diagnosis, prescription, or recommendation. Posted content and comments do not create a doctor-patient relationship between Dr. Cassone and the viewer.  Those who view or engage should not make any lifestyle changes before first consulting a physician and obtaining a medical exam, diagnosis, and personal recommendation.  Always seek the advice of a physician, or other qualified health provider, with any questions regarding medical conditions. Dr. Cassone is not liable or responsible for any advice, course of treatment, diagnosis or any other information, services or products you obtain.]",
			"dob": "",
			"gender": "",
			"city": "Temecula, Ca.",
			"merchant": false,
			"boostProPlus": false,
			"fb": false,
			"mature": "0",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [{
				"key": "other",
				"value": "https:\/\/www.amazon.com\/Dr.-Cassone\/e\/B00J2HJX6Y\/ref=sr_ntt_srch_lnk_1?qid=1542295447&sr=8-1"
			}],
			"feature_flags": false,
			"programs": [],
			"plus": false,
			"hashtags": false,
			"verified": true,
			"founder": false,
			"disabled_boost": true,
			"boost_autorotate": false,
			"categories": [],
			"wire_rewards": {
				"description": "Thank you for your support! ",
				"rewards": {
					"points": [],
					"money": [],
					"tokens": [{
						"amount": "1",
						"description": "I very much appreciate your kindness and will use your donation to post awesome content."
					}, {
						"amount": "5",
						"description": "I will mention your channel in a post as a great show of gratitude. If you're lucky I will boost it."
					}, {
						"amount": "10",
						"description": "Your name will appear in my bio section as a supporter for the next six months. "
					}]
				}
			},
			"pinned_posts": ["946612051418996736", "941137053490614272", "964335278414299136"],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "8",
			"last_avatar_upload": "0",
			"canary": true,
			"theme": "dark",
			"onchain_booster": "1563466121",
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"chat": true,
			"urn": "urn:user:902355209638912004",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "1",
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"eth_wallet": "0x9851dad5c623558e0c9d2292f54f49ff019d9dd1",
			"rating": "1"
		},
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 0,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false
		},
		"wire_threshold": "0",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1022521168192323584\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMjUyMTE2ODE5MjMyMzU4NFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.CWD-taCXTaTkf1BG1dc0GyvHHVF0O5I3p9QdW-QWMF0",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 768,
		"height": 383,
		"gif": false,
		"time_sent": 1569164044,
		"urn": "urn:image:1022521168192323584",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1022521168192323584\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMjUyMTE2ODE5MjMyMzU4NFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.CWD-taCXTaTkf1BG1dc0GyvHHVF0O5I3p9QdW-QWMF0",
		"description": null
	}, {
		"guid": "1021922743450447872",
		"type": "object",
		"subtype": "image",
		"time_created": "1571619900",
		"time_updated": "1569021582",
		"container_guid": "828740569485484032",
		"owner_guid": "828345190770024459",
		"access_id": "2",
		"nsfw": [],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "Boiler Room\n\nFractal Art Wallpaper created with Mandelbulb3D using Parameters by @DsyneGrafix from a couple days ago. Thanks for those tricky Parameters bro! I enjoyed the challenge! \nBest Viewed Full Screen! \n\n#FractalArt #Original #Fractalizer #Mandelbulb3D #Minds ",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "828345190770024459",
			"type": "user",
			"subtype": false,
			"time_created": "1522868883",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": ["fractalart", "fractalizer", "art", "original", "OfficialGifs"],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "fractalizer",
			"username": "fractalizer",
			"language": "en",
			"icontime": "1566547745",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Account created on: Apr 4, 2018\n\nFractal Artist\nCreating Trippy Art Is My Mission\nJWildfire and Mandelbulb3D are my favourite Fractal Editors.\n\nThere's plenty of Fractal Art Wallpapers on my website at \nhttp:\/\/www.fractaldesigns.net\nYou will also find links to other websites where my art is featured.\nUltra High Definition Images Available Free to use on your personal desktop computer or mobile devices\nhttp:\/\/fractaldesigns.net\/ultra-high-definition-3840x2160p\/\n\nIf you are interested in printed products featured with my art, you can find links to Zazzle and Redbubble there too!\n\nFractal Art Group\n\nhttps:\/\/www.minds.com\/groups\/profile\/828740569485484032\n\n\nColouring The World Group\n\nhttps:\/\/www.minds.com\/groups\/profile\/875507690911694848\n\nI appreciate all support that you can provide,\nThank You!\nhttps:\/\/paypal.me\/CraigBak\nSpecial Custom Designs Upon Request For Print",
			"dob": "",
			"gender": "",
			"city": "Thetford",
			"merchant": {
				"exclusive": {
					"background": "1568869769",
					"intro": ""
				}
			},
			"boostProPlus": false,
			"fb": false,
			"mature": "0",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [],
			"feature_flags": false,
			"programs": [],
			"plus": false,
			"hashtags": false,
			"verified": true,
			"founder": false,
			"disabled_boost": false,
			"boost_autorotate": true,
			"categories": [],
			"wire_rewards": {
				"description": "",
				"rewards": {
					"points": [],
					"money": [],
					"tokens": [{
						"amount": "5",
						"description": "For 5 tokens You will receive a custom Fractal Art Image created especially for you in a high quantity 1080p render. Please remember,  I will send a Private Message to you with a link to download your image."
					}]
				}
			},
			"pinned_posts": ["961774654586200064", "972986661160710144", "997707293036769280"],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "8",
			"last_avatar_upload": "0",
			"canary": true,
			"theme": "dark",
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"chat": true,
			"urn": "urn:user:828345190770024459",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "2",
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"onchain_booster": "0",
			"eth_wallet": "0xfB797a92B7435f6aDDCF136a0Aa13F2153AfcFA7",
			"rating": "1"
		},
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 1,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false
		},
		"wire_threshold": "0",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1021922743450447872\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMTkyMjc0MzQ1MDQ0Nzg3MlwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.deq5348Tbt4s47Ynl2kExmXnS6ilVNUukZo9GMDzuXo",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 1440,
		"height": 810,
		"gif": false,
		"time_sent": 1569021368,
		"urn": "urn:image:1021922743450447872",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1021922743450447872\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMTkyMjc0MzQ1MDQ0Nzg3MlwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.deq5348Tbt4s47Ynl2kExmXnS6ilVNUukZo9GMDzuXo",
		"description": null
	}, {
		"guid": "1025321177702203392",
		"type": "object",
		"subtype": "image",
		"time_created": "1570881600",
		"time_updated": "1569832073",
		"container_guid": "1011430374300983299",
		"owner_guid": "1011430374300983299",
		"access_id": "2",
		"nsfw": [],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "Anubastis:  This was a commission from Shendude, and I love ancient Egypt, so I enjoyed depicting a couple of lasses from his Egypt-esque fantasy setting.  One of them even made it to my banner.\n\n\ud83c\udf96 If you're a good guy who enjoys drawings like this, you can give it a thumbs-up, comment, subscribe, wire me some lightning, or buy me a Ko-Fi ( https:\/\/ko-fi.com\/malcolmd ).\n\n#ancientegypt #nsfw #catgirl #hentai #monstergirl \u30d5\u30a1\u30f3\u30bf\u30b8\u30fc, fantasy, \u4eba\u5916\u5a18, \u30e2\u30f3\u30b9\u30bf\u30fc\u5a18 \u732b\u5a18, dog-girl, \u7363\u5a18, kemonomimi, anthro, cat ears, \u30ec\u30ba, \u767e\u5408, lesbian, \u30a2\u30cc\u30d3\u30b9\u5a18, female Anubis, jackal, \u30d0\u30b9\u30c6\u30c8, Bast, \u30bb\u30af\u30e1\u30c8, Sekhmet, Egyptian magic wand, two girls, \u3042\u3066\u3066\u3093\u306e\u3088, breast press, \u304a\u5c3b, ass, bum, butt, MalcolmDouglas, MalcolmD",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "1011430374300983299",
			"type": "user",
			"subtype": false,
			"time_created": "1566519792",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": [],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "MalcolmD",
			"username": "malcolmd",
			"language": "en",
			"icontime": "1567030876",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Hentai artist",
			"dob": "",
			"gender": "",
			"city": "",
			"merchant": false,
			"boostProPlus": false,
			"fb": false,
			"mature": "1",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [],
			"feature_flags": false,
			"programs": [],
			"plus": false,
			"hashtags": false,
			"verified": false,
			"founder": false,
			"disabled_boost": false,
			"boost_autorotate": true,
			"categories": [],
			"wire_rewards": null,
			"pinned_posts": [],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "7",
			"last_avatar_upload": "1566521762",
			"canary": true,
			"theme": false,
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"urn": "urn:user:1011430374300983299",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "1",
			"pro": false,
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"onchain_booster": "0",
			"eth_wallet": "",
			"rating": "1"
		},
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 0,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false,
			"paywall": false
		},
		"wire_threshold": "",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1025321177702203392\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyNTMyMTE3NzcwMjIwMzM5MlwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.kug4I07N-2TIgk0TSl8h2kl2J7owmANvqJicOp8Grmw",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 1032,
		"height": 1080,
		"gif": false,
		"time_sent": 1569831618,
		"urn": "urn:image:1025321177702203392",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1025321177702203392\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyNTMyMTE3NzcwMjIwMzM5MlwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.kug4I07N-2TIgk0TSl8h2kl2J7owmANvqJicOp8Grmw",
		"description": null
	}, {
		"guid": "1021943743360253952",
		"type": "object",
		"subtype": "image",
		"time_created": "1570579200",
		"time_updated": "1569026678",
		"container_guid": "902355209638912004",
		"owner_guid": "902355209638912004",
		"access_id": "2",
		"nsfw": [],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "Psychomusicology\nA science linking both musical structure and process (in the sense of \"musical activity\"). It aims to explain and understand musical behavior and experience, including the processes through which music is perceived, created, responded to, and incorporated into everyday life.\n\n[Tan, Siu-Lan; Pfordresher, Peter; Harr\u00e9, Rom (2010). Psychology of Music: From Sound to Significance. New York: Psychology Press. p. 2. ISBN 978-1-84169-868-7]\n#music #psychology #medicine",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "902355209638912004",
			"type": "user",
			"subtype": false,
			"time_created": "1540514246",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": ["medicine", "health", "science", "stem", "nutrition"],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "Dr. Cassone",
			"username": "drcassone",
			"language": "en",
			"icontime": "1568521928",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Cassone\n(pronouced: kuh\u00b7so\u00b7nee)\n\nWelcome to my favorite social media site. I am here on Minds as an educator with the goal of creating great content for you.\n\n#medicine #science #nutrition \n\nABOUT\nI hold two master\u2019s degrees in health sciences, a PhD in clinical nutrition, a second doctorate in integrative medicine (DAOM), and am a board certified licensed primary care provider in the state of California running a thriving private practice. I also have a teaching position at South Baylo University educating\u00a0licensed providers, have written three books, and am the owner and operator of a private gym called Range of Motion which I opened in 2000.\n\n\u201cAs a scientist and a researcher, it has been my life\u2019s work to sort effectual from ineffectual treatment models. As a doctor, it is my art to investigate the complex origins of each patient\u2019s condition and to apply techniques of corrective physiology. It is only by understanding and treating the root cause that long term health is possible.\u201d - Dr. Cassone\n\nMAIN WEBSITE\nhttps:\/\/www.cassonewellness.com\/ \n________________________________\nGROUPS\n\nFERMENTED FOODS\nhttps:\/\/www.minds.com\/groups\/profile\/909827446092017664\/feed\n\nRESET Food Plan\nhttps:\/\/www.minds.com\/groups\/profile\/907272216328880128\/feed\n\nMEDICINE: Quiz Yourself\nhttps:\/\/www.minds.com\/groups\/profile\/938541470676492288\/feed\n\nSMOOTHIES\nhttps:\/\/www.minds.com\/groups\/profile\/912825469371117568\/feed\n_____________________________\nTOP CONTRIBUTORS\n\n@Annaroper\n@GreenDeen\n@FloatingOnSmiles\n@peninsolar\n@delastman\n@MinnieApolis\n@IndianaJames\n@TheronH\n@mindofmyown\n@FaizanKhan\n@mindsplus\n@drpatricklockwood\n@Luculent\n@Willieleev1971\n@nkrpoetry\n_____________________________\nDisclaimer:\n[Dr. Cassone's title of \"doctor\" or \u201cDr.\u201d refers to the above mentioned academic degrees. All content posted is for general informational purposes only and should not be used to self-diagnose and it is not a substitute for a medical exam, cure, treatment, diagnosis, prescription, or recommendation. Posted content and comments do not create a doctor-patient relationship between Dr. Cassone and the viewer.  Those who view or engage should not make any lifestyle changes before first consulting a physician and obtaining a medical exam, diagnosis, and personal recommendation.  Always seek the advice of a physician, or other qualified health provider, with any questions regarding medical conditions. Dr. Cassone is not liable or responsible for any advice, course of treatment, diagnosis or any other information, services or products you obtain.]",
			"dob": "",
			"gender": "",
			"city": "Temecula, Ca.",
			"merchant": false,
			"boostProPlus": false,
			"fb": false,
			"mature": "0",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [{
				"key": "other",
				"value": "https:\/\/www.amazon.com\/Dr.-Cassone\/e\/B00J2HJX6Y\/ref=sr_ntt_srch_lnk_1?qid=1542295447&sr=8-1"
			}],
			"feature_flags": false,
			"programs": [],
			"plus": false,
			"hashtags": false,
			"verified": true,
			"founder": false,
			"disabled_boost": true,
			"boost_autorotate": false,
			"categories": [],
			"wire_rewards": {
				"description": "Thank you for your support! ",
				"rewards": {
					"points": [],
					"money": [],
					"tokens": [{
						"amount": "1",
						"description": "I very much appreciate your kindness and will use your donation to post awesome content."
					}, {
						"amount": "5",
						"description": "I will mention your channel in a post as a great show of gratitude. If you're lucky I will boost it."
					}, {
						"amount": "10",
						"description": "Your name will appear in my bio section as a supporter for the next six months. "
					}]
				}
			},
			"pinned_posts": ["946612051418996736", "941137053490614272", "964335278414299136"],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "8",
			"last_avatar_upload": "0",
			"canary": true,
			"theme": "dark",
			"onchain_booster": "1563466121",
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"chat": true,
			"urn": "urn:user:902355209638912004",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "1",
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"eth_wallet": "0x9851dad5c623558e0c9d2292f54f49ff019d9dd1",
			"rating": "1"
		},
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 0,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false
		},
		"wire_threshold": "0",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1021943743360253952\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMTk0Mzc0MzM2MDI1Mzk1MlwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.m5SEVh-Cd6LLHYng4ZslCScp9hNE3rrUoYstiJ638w4",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 480,
		"height": 270,
		"gif": true,
		"time_sent": 1569026375,
		"urn": "urn:image:1021943743360253952",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1021943743360253952\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMTk0Mzc0MzM2MDI1Mzk1MlwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.m5SEVh-Cd6LLHYng4ZslCScp9hNE3rrUoYstiJ638w4",
		"description": null
	}, {
		"guid": "1021636956555587584",
		"type": "object",
		"subtype": "image",
		"time_created": "1570536000",
		"time_updated": "1568954034",
		"container_guid": "1011430374300983299",
		"owner_guid": "1011430374300983299",
		"access_id": "2",
		"nsfw": [],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "Leprechaun Mischief 3 (dad-daughter incest, mind control).\n\n\ud83c\udf96 If you're a good guy who enjoys drawings like this, you can give it a thumbs-up, comment, subscribe, wire me some lightning, or buy me a Ko-Fi ( https:\/\/ko-fi.com\/malcolmd ).\n\n#nsfw #hentai #incest #mindcontrol #fatherdaughter father daughter dad_daughter eroticart agedifference teen dilf leprechaun hypnosis pubichair shockwave megatron",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "1011430374300983299",
			"type": "user",
			"subtype": false,
			"time_created": "1566519792",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": [],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "MalcolmD",
			"username": "malcolmd",
			"language": "en",
			"icontime": "1567030876",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Hentai artist",
			"dob": "",
			"gender": "",
			"city": "",
			"merchant": false,
			"boostProPlus": false,
			"fb": false,
			"mature": "1",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [],
			"feature_flags": false,
			"programs": [],
			"plus": false,
			"hashtags": false,
			"verified": false,
			"founder": false,
			"disabled_boost": false,
			"boost_autorotate": true,
			"categories": [],
			"wire_rewards": null,
			"pinned_posts": [],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "7",
			"last_avatar_upload": "1566521762",
			"canary": true,
			"theme": false,
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"urn": "urn:user:1011430374300983299",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "1",
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"onchain_booster": "0",
			"eth_wallet": "",
			"rating": "1"
		},
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 0,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false,
			"paywall": false
		},
		"wire_threshold": "",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1021636956555587584\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMTYzNjk1NjU1NTU4NzU4NFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.s3P9fn_osg2Z6ShqoOz2rh7icAmdImVBvfLMhseAGPQ",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 1920,
		"height": 1080,
		"gif": false,
		"time_sent": 1568953231,
		"urn": "urn:image:1021636956555587584",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1021636956555587584\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMTYzNjk1NjU1NTU4NzU4NFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.s3P9fn_osg2Z6ShqoOz2rh7icAmdImVBvfLMhseAGPQ",
		"description": null
	}, {
		"guid": "1024810855308238848",
		"type": "object",
		"subtype": "image",
		"time_created": "1570485600",
		"time_updated": "1569710003",
		"container_guid": "805147376808370194",
		"owner_guid": "805147376808370194",
		"access_id": "2",
		"nsfw": [],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "The page exposing porn star Gail Thackray, who promotes sex pervert Mas Sajady, got an unusual number of hits last week. No doubt because a protester was warning future Sajady victims that this is the type of amoral person he associates with.\n\nhttps:\/\/massajadyclassactionlawsuit.wordpress.com\/gail-thackray-bridgetta-tomarchio-mas-sajadys-sleazy-porn-star-promoters\/",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "805147376808370194",
			"type": "user",
			"subtype": false,
			"time_created": "1517338093",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": [],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "Mas Sajady Class Action Lawsuit",
			"username": "MasSajadyClassActionLawsuit",
			"language": "en",
			"icontime": "1517340987",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Researching and compiling information for a class action lawsuit. If you are a dissatisfied client, we would like to hear from you.\n\nwww.MasSajadyClassActionLawsuit.wordpress.com\n",
			"dob": "",
			"gender": "",
			"city": "",
			"merchant": false,
			"boostProPlus": false,
			"fb": false,
			"mature": "0",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [],
			"feature_flags": false,
			"programs": [],
			"plus": false,
			"hashtags": false,
			"verified": false,
			"founder": false,
			"disabled_boost": false,
			"boost_autorotate": true,
			"categories": [],
			"wire_rewards": null,
			"pinned_posts": ["953666495143636992", "1022711842583195648"],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "0",
			"last_avatar_upload": "0",
			"canary": true,
			"theme": "light",
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"chat": true,
			"urn": "urn:user:805147376808370194",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "1",
			"pro": false,
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"onchain_booster": "0",
			"eth_wallet": "",
			"rating": "1"
		},
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 0,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false
		},
		"wire_threshold": "0",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1024810855308238848\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyNDgxMDg1NTMwODIzODg0OFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.9_mTyOw1NNoLSdGCVni00_4wmffCvvSI7qx8VJni620",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 519,
		"height": 127,
		"gif": false,
		"time_sent": 1569709947,
		"urn": "urn:image:1024810855308238848",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1024810855308238848\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyNDgxMDg1NTMwODIzODg0OFwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.9_mTyOw1NNoLSdGCVni00_4wmffCvvSI7qx8VJni620",
		"description": null
	}, {
		"guid": "1021787307043905536",
		"type": "object",
		"subtype": "image",
		"time_created": "1570456800",
		"time_updated": "1568989555",
		"container_guid": "902355209638912004",
		"owner_guid": "902355209638912004",
		"access_id": "2",
		"nsfw": [],
		"nsfw_lock": [],
		"allow_comments": true,
		"title": "Depression Types\n\u27a4  Persistent depressive disorder: (also called dysthymia) is a depressed mood that lasts for at least two years. \n\u27a4  Postpartum depression: relatively mild depressive and anxiety symptoms that typically clear within two weeks after delivery. \n\u27a4  Psychotic depression: occurs when a person has severe depression plus some form of psychosis, such as having disturbing false fixed beliefs (delusions) or hearing or seeing upsetting things that others cannot hear or see (hallucinations). \n\u27a4  Seasonal affective disorder is characterized by the onset of depression during the winter months, when there is less natural sunlight. \n\u27a4  Bipolar disorder is different from depression, but it is included in this list is because someone with bipolar disorder experiences episodes of extremely low moods that meet the criteria for major depression (called \u201cbipolar depression\u201d). But a person with bipolar disorder also experiences extreme high \u2013 euphoric or irritable \u2013 moods called \u201cmania\u201d or a less severe form called \u201chypomania.\u201d\n[National Institute of Mental Health]\n#health #medicine #psychology",
		"featured": false,
		"featured_id": false,
		"ownerObj": {
			"guid": "902355209638912004",
			"type": "user",
			"subtype": false,
			"time_created": "1540514246",
			"time_updated": false,
			"container_guid": "0",
			"owner_guid": "0",
			"site_guid": false,
			"access_id": "2",
			"tags": ["medicine", "health", "science", "stem", "nutrition"],
			"nsfw": [],
			"nsfw_lock": [],
			"allow_comments": false,
			"name": "Dr. Cassone",
			"username": "drcassone",
			"language": "en",
			"icontime": "1568521928",
			"legacy_guid": false,
			"featured_id": false,
			"banned": "no",
			"ban_reason": false,
			"website": "",
			"briefdescription": "Cassone\n(pronouced: kuh\u00b7so\u00b7nee)\n\nWelcome to my favorite social media site. I am here on Minds as an educator with the goal of creating great content for you.\n\n#medicine #science #nutrition \n\nABOUT\nI hold two master\u2019s degrees in health sciences, a PhD in clinical nutrition, a second doctorate in integrative medicine (DAOM), and am a board certified licensed primary care provider in the state of California running a thriving private practice. I also have a teaching position at South Baylo University educating\u00a0licensed providers, have written three books, and am the owner and operator of a private gym called Range of Motion which I opened in 2000.\n\n\u201cAs a scientist and a researcher, it has been my life\u2019s work to sort effectual from ineffectual treatment models. As a doctor, it is my art to investigate the complex origins of each patient\u2019s condition and to apply techniques of corrective physiology. It is only by understanding and treating the root cause that long term health is possible.\u201d - Dr. Cassone\n\nMAIN WEBSITE\nhttps:\/\/www.cassonewellness.com\/ \n________________________________\nGROUPS\n\nFERMENTED FOODS\nhttps:\/\/www.minds.com\/groups\/profile\/909827446092017664\/feed\n\nRESET Food Plan\nhttps:\/\/www.minds.com\/groups\/profile\/907272216328880128\/feed\n\nMEDICINE: Quiz Yourself\nhttps:\/\/www.minds.com\/groups\/profile\/938541470676492288\/feed\n\nSMOOTHIES\nhttps:\/\/www.minds.com\/groups\/profile\/912825469371117568\/feed\n_____________________________\nTOP CONTRIBUTORS\n\n@Annaroper\n@GreenDeen\n@FloatingOnSmiles\n@peninsolar\n@delastman\n@MinnieApolis\n@IndianaJames\n@TheronH\n@mindofmyown\n@FaizanKhan\n@mindsplus\n@drpatricklockwood\n@Luculent\n@Willieleev1971\n@nkrpoetry\n_____________________________\nDisclaimer:\n[Dr. Cassone's title of \"doctor\" or \u201cDr.\u201d refers to the above mentioned academic degrees. All content posted is for general informational purposes only and should not be used to self-diagnose and it is not a substitute for a medical exam, cure, treatment, diagnosis, prescription, or recommendation. Posted content and comments do not create a doctor-patient relationship between Dr. Cassone and the viewer.  Those who view or engage should not make any lifestyle changes before first consulting a physician and obtaining a medical exam, diagnosis, and personal recommendation.  Always seek the advice of a physician, or other qualified health provider, with any questions regarding medical conditions. Dr. Cassone is not liable or responsible for any advice, course of treatment, diagnosis or any other information, services or products you obtain.]",
			"dob": "",
			"gender": "",
			"city": "Temecula, Ca.",
			"merchant": false,
			"boostProPlus": false,
			"fb": false,
			"mature": "0",
			"monetized": "",
			"signup_method": false,
			"social_profiles": [{
				"key": "other",
				"value": "https:\/\/www.amazon.com\/Dr.-Cassone\/e\/B00J2HJX6Y\/ref=sr_ntt_srch_lnk_1?qid=1542295447&sr=8-1"
			}],
			"feature_flags": false,
			"programs": [],
			"plus": false,
			"hashtags": false,
			"verified": true,
			"founder": false,
			"disabled_boost": true,
			"boost_autorotate": false,
			"categories": [],
			"wire_rewards": {
				"description": "Thank you for your support! ",
				"rewards": {
					"points": [],
					"money": [],
					"tokens": [{
						"amount": "1",
						"description": "I very much appreciate your kindness and will use your donation to post awesome content."
					}, {
						"amount": "5",
						"description": "I will mention your channel in a post as a great show of gratitude. If you're lucky I will boost it."
					}, {
						"amount": "10",
						"description": "Your name will appear in my bio section as a supporter for the next six months. "
					}]
				}
			},
			"pinned_posts": ["946612051418996736", "941137053490614272", "964335278414299136"],
			"is_mature": false,
			"mature_lock": false,
			"last_accepted_tos": "1558597098",
			"opted_in_hashtags": "8",
			"last_avatar_upload": "0",
			"canary": true,
			"theme": "dark",
			"onchain_booster": "1563466121",
			"toaster_notifications": true,
			"mode": "0",
			"btc_address": "",
			"chat": true,
			"urn": "urn:user:902355209638912004",
			"subscribed": false,
			"subscriber": false,
			"boost_rating": "1",
			"rewards": true,
			"p2p_media_enabled": false,
			"is_admin": false,
			"eth_wallet": "0x9851dad5c623558e0c9d2292f54f49ff019d9dd1",
			"rating": "1"
		},
		"category": false,
		"comments:count": false,
		"thumbs:up:count": 0,
		"thumbs:up:user_guids": false,
		"thumbs:down:count": 0,
		"thumbs:down:user_guids": false,
		"flags": {
			"mature": false
		},
		"wire_threshold": "0",
		"thumbnail": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1021787307043905536\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMTc4NzMwNzA0MzkwNTUzNlwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.s-dtqnFBWsHbPR76blxdHflquHSfdXFIaYzg2xJFxmg",
		"cinemr_guid": false,
		"license": false,
		"mature": false,
		"boost_rejection_reason": -1,
		"rating": 2,
		"width": 2391,
		"height": 1593,
		"gif": false,
		"time_sent": 1568989077,
		"urn": "urn:image:1021787307043905536",
		"thumbnail_src": "https:\/\/cdn.minds.com\/fs\/v1\/thumbnail\/1021787307043905536\/xlarge?jwtsig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzUxNTg0MDAsInVyaSI6Imh0dHBzOlwvXC9jZG4ubWluZHMuY29tXC9mc1wvdjFcL3RodW1ibmFpbFwvMTAyMTc4NzMwNzA0MzkwNTUzNlwveGxhcmdlIiwidXNlcl9ndWlkIjoiOTQ1NjYxMzU5NDUyODU2MzIxIn0.s-dtqnFBWsHbPR76blxdHflquHSfdXFIaYzg2xJFxmg",
		"description": null
	}];
  requestParams = {
    // TODO @abhijeet check for all valid request params
    taxonomies: 'activity',
    offset: '',
    limit: 10,
    q: ''
  };
  channel: any;
  username: string;
  inProgress = false;
  moreData: any;

  constructor(
    private route: ActivatedRoute,
    private client: Client
  ) { }

  ngOnInit() {
    this.paramsSub = this.route.params.subscribe((params) => {
      this.username = params['username'];
      this.requestParams.q = '#portfolio' + params['username'];
      this.loadProfileInfo();
    });
  }

  loadProfileInfo() {
    this.client.get(`api/v1/channel/${this.username}`)
      .then((response: any) => {
        this.channel = response['channel'];
        this.loadPortfolio();
      })
      .catch(e => {
        console.error('Error: ', e);
      });
  }

  loadPortfolio() {
    this.client.get('api/v2/search', this.requestParams)
      .then((response: any) => {
        this.inProgress = false;
        // TODO @debjeet continue here
        // this.entities = response['entities'];
        console.log('Search result: ', response);
      })
      .catch(e => {
        console.error('Error: ', e);
      });
  }

  ngOnDestroy() {
    this.paramsSub.unsubscribe();
  }

  async searchMore(refresh: boolean = false) {
    if (this.inProgress) {
      return;
    }
    if (refresh) {
      this.offset = '';
    }
    this.inProgress = true;
    this.client.get('api/v2/search', { q: this.q,limit: 12, offset: this.offset, type:`object:${this.type}` }, { cache: true })
      .then((data) => {
        if (!data) {
          this.moreData = false;
          this.inProgress = false;
          return false;
        }
        if (this.entities && !refresh) {
          console.log('added data')
        //   this.entities = this.entities.concat(this.entities1);
        } else {
          console.log('added new data')
        //   this.entities = this.entities1;
        }
        this.offset = data['load-next'];
        this.inProgress = false;
      })
      .catch((e) => {
        this.inProgress = false;
      });
  }

}
